### PR TITLE
Bump tolerance for `fuzz_calculate_spot_price_after_short`

### PR DESCRIPTION
**Pull request by ryangoree**
# Description

The `fuzz_calculate_spot_price_after_short` test was intermittently failing with it's current tolerance of `fixed!(1e10)`. This PR bumps it to `fixed!(1e11)`.

### Rust

- [ ] **Testing**
    - [ ] Are there new or updated unit or integration tests?
    - [ ] Do the tests cover the happy paths?
    - [ ] Do the tests cover the unhappy paths?
    - [ ] Are there an adequate number of fuzz tests to ensure that we are
          covering the full input space?
    - [ ] If matching Solidity behavior, are there differential fuzz tests that
          ensure that Rust matches Solidity?

### CODE REVIEW

**Comment by mcclurejt** [comment]
any idea as to why this started happening?

**Review by dpaiton — APPROVED** [review]

**Comment by dpaiton** [comment]
> any idea as to why this started happening?

I think 1e11 (aka correct up to the 8th decimal) is pretty reasonable given that the spot price itself is an approximation of the realized price for a non-infinitesimal trade size.

That being said, AFAIK this was not failing before the latest flurry of activity in the rust repo. I'm going to approve to unblock other PRs from landing with this failing, but I think we should keep it in mind in case we start seeing more failures.

**Comment by ryangoree** [comment]
> That being said, AFAIK this was not failing before the latest flurry of activity in the rust part of the repo.

Because the test added in the flurry #919

**Comment by dpaiton** [comment]
I absorbed this PR into https://github.com/delvtech/hyperdrive/pull/938 so that we could have both fixes in one PR and CI would pass. Closing this issue.

**Pull request closed without merging**
